<!DOCTYPE html>
<html
  xmlns="http://www.w3.org/1999/xhtml"
  lang=""
  xml:lang=""
  >
  <head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-5541738-17"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-5541738-17');
    </script>

    <meta charset="utf-8" />
    <meta name="generator" content="pandoc" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, user-scalable=yes"
    />
           <title>Why am getting “site can’t be reached” when I try to access my Jupyter notebook?</title>
    <style>
      code{white-space: pre-wrap;}
      span.smallcaps{font-variant: small-caps;}
      span.underline{text-decoration: underline;}
      div.column{display: inline-block; vertical-align: top; width: 50%;}
      div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
      ul.task-list{list-style: none;}
      .display.math{display: block; text-align: center; margin: 0.5rem auto;}
    </style>
        <link rel="stylesheet" href="../style/bulma.css" />
        <link rel="stylesheet" href="../style/custom.css" />
     
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv-printshiv.min.js"></script>
    <![endif]-->
    
  </head>
  <body>
         <!-- <header id="title-block-header">
      <h1 class="title">Why am getting “site can’t be reached” when I try to access my Jupyter notebook?</h1>
            </header> -->
    <section class="section">
      <div class="container">
        <div class="content">
                      <p style="text-align: center"><a href="../class-04/">← back to class-04</a></p>
          
                      <h1>Why am getting “site can’t be reached” when I try to access my Jupyter notebook?</h1>
             
<figure>
<img src="../images/site-cant-be-reached.png" alt="Site can’t be reached" /><figcaption aria-hidden="true">Site can’t be reached</figcaption>
</figure>
<p>One error you might get when trying to visit your list of notebooks is <strong>This site can’t be reached: localhost refused to connect.</strong></p>
<pre><code>This site can’t be reached

localhost refused to connect.

Try:

Checking the connection
Checking the proxy and the firewall

ERR_CONNECTION_REFUSED</code></pre>
<p>This happens because you shut down your Jupyter server, so the URL at <code>http://localhost:8888</code> doesn’t work any more. You probably closed the a Terminal window or pressed Ctrl+C to go run other commands.</p>
<p>To fix this, you’ll need to start a new notebook server by running <code>jupyter notebook</code> on the command line. This will start a new server and the <a href="http://localhost:8888">http://localhost:8888</a> sites will start working again.</p>

        <p style="text-align: center; margin-top: 4em;"><a href="../class-04/">← back to class-04</a></p>
    
      </div>
      </div>
    </section>
    
  </body>
</html>
